services:
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - 8080:80
            
    pgdatabase:
        image: postgres:13
        environment: 
            - POSTGRES_USER=root 
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=ny_taxi
        volumes:
            - "C:\\Users\\ishan\\Desktop\\dataEng Zoomcamp\\week_01\\ny_taxi_pg_data:/var/lib/postgresql/data:rw" 
        ports:
            - 5432:5432